### ISSUE TITLE
需要一个预览版分支给   Avalonia 11.0.0-preview6  (Need a preview branch for Avalonia 11.0.0 preview6)

### ISSUE THREAD

**Issue by yangjieshao** [kekyo/SkiaImageView.Wpf#2]
https://github.com/yangjieshao/SkiaImageView

**Comment by mimimiaomiao1** [comment]
> 

<img width="672" alt="image" src="https://user-images.githubusercontent.com/58240619/236102363-30249f62-f1c3-4f9f-9075-cc43a40a2816.png">

我的也是11.0预览版.还不支持. 请问怎么弄可以使用?

**Comment by yangjieshao** [comment]
> > 
> 
> <img alt="image" width="672" src="https://user-images.githubusercontent.com/58240619/236102363-30249f62-f1c3-4f9f-9075-cc43a40a2816.png">
> 
> 我的也是11.0预览版.还不支持. 请问怎么弄可以使用?



不是让你用我的分支了么

**Comment by mimimiaomiao1** [comment]
> > > 
> > 
> > 
> > <img alt="image" width="672" src="https://user-images.githubusercontent.com/58240619/236102363-30249f62-f1c3-4f9f-9075-cc43a40a2816.png">
> > 我的也是11.0预览版.还不支持. 请问怎么弄可以使用?
> 
> 不是让你用我的分支了么

我的是preview5 可以用吗?

**Comment by yangjieshao** [comment]
> 

那就只能自己fork一个然后改了 问题不大

**Comment by mimimiaomiao1** [comment]
> > 
> 
> 那就只能自己fork一个然后改了 问题不大

我现在是搭配的prism再用. 我还是先不搞了,等avalonia11正式版我再弄吧.

**Comment by yangjieshao** [comment]
> 我现在是搭配的prism再用. 我还是先不搞了,等avalonia11正式版我再弄吧.

我更新了一下 你试试呗

**Comment by mimimiaomiao1** [comment]
> > 我现在是搭配的prism再用. 我还是先不搞了,等avalonia11正式版我再弄吧.
> 
> 我更新了一下 你试试呗

能否提供一下Q或者微信啥的...想请教一下avalonia相关的事

**Comment by kekyo** [comment]
SkiaImageView 1.5.0 released. Included Avalonia 11.
Thanks, reopen when you want to discussion additional issue.
